export const TwilightStatId = {
  Hp: "hp",
  Attack: "attack",
  Defense: "defense",
  ArmorPiercing: "armorPiercing",
  Crit: "crit",
  CritResistance: "critResistance",
  ElementalDamage: "elementalDamage",
  ElementalArmor: "elementalArmor",
  HpSteal: "hpSteal",
  DamageReflect: "damageReflect",
  TrueDamage: "trueDamage",
  TrueArmor: "trueArmor",
  DodgeRate: "dodgeRate",
  HitRate: "hitRate",
  CritRate: "critRate",
  CritResistanceRate: "critResistanceRate",
  PiercingRate: "piercingRate",
  PiercingResistance: "piercingResistance",
  ComboRate: "comboRate",
  ComboResistanceRate: "comboResistanceRate",
  PiercingBonus: "piercingBonus",
  PiercingReduction: "piercingReduction",
  BlockRate: "blockRate",
  BlockBreakRate: "blockBreakRate",
  CritDamage: "critDamage",
  DamageReductionFlat: "damageReductionFlat",
  ComboDamageRatio: "comboDamageRatio",
  ComboDamageReduction: "comboDamageReduction",
  BlockDamageImmunity: "blockDamageImmunity",
  BlockPenetrate: "blockPenetrate",
  DamageBonus: "damageBonus",
  DamageReductionRate: "damageReductionRate",
  PlayerDamageBoost: "playerDamageBoost",
  PlayerDamageReduction: "playerDamageReduction"
} as const;

export type TwilightStatId =
  (typeof TwilightStatId)[keyof typeof TwilightStatId];
